language: ruby
rvm: 2.3.0
sudo: false
cache: bundler
script: ./bin/rake
addons:
  code_climate:
    repo_token:
      secure: JjKduNPiC5RthzQnrn4Awloomfm3P9kyEmW6Bzv2vrGxkpw98xXasTUwR+fCPqxgFxJqwSk1yTe3DHaMH2T63e+JFPre3pV5hHh1uNrnDR966TsVLe1d/0QXGmntRgo5ZVGLosQCKIhV7nFXl4TQ6A40SxcrSO+raMtXF6+KJ/VVbOXOVEGB93TjuVe5K5EsXDZNYZdLrBAUQzHXhkBCQhLhZTgyIvdDWlsgpXmVqDQ9PJMW6E18hZGtWF+9GNTlMtYcuberRllRi4ZNZmerzeD7UDVvkwUpeU/goyKHmgSIi/YkEDPOCKhfzfl9aqq+mFTn/P4WfMY0D7A1yVKInS2A2zHMyVlLJ3/VketRJhdvYD1XkAUa9Fm3ESLMVJaLT7C09ut9gZnQ4tDpjAGQKxUwfr5edcjAuv9Nvk66igCdDamFmmIMBCHEoa8DatNVXECDOhkrosIFF9GXeDiTrzyI+hKKd21fMptR7r9yNoreq2h8fN1k4bHS0CdG8F4ZFDLHOD0cQRrXhKJ5EQZwqpRZe34Xem0xp/fdPCNWiDGDNAv045S0jPvNExqZrCyQlvGZuONbLYEP3NXVI+snnXUDh90r5L4xlL+yVrG/K99XRrUgWeqv0l/bSFlyE+IfhklX8z8q9S7WwMj04JxaSKWg57D9AQnDQZrIq5ye8Rk=
deploy:
  - provider: heroku # staging (dev.waxpoeticrecords.com)
    api_key:
      secure: k0UI3UjH1CESus6bSA9jd0IBm0TappHKxOq4BsraBJSKEzHF/DShFiNcbYXn/Vlo5qXBlepWjGeao5i3O0UToiHGECN7GCp3JeEhm3LG7+HkOKKxEYBaVw3ynVeBseTVnyqFxvWL2+WTJddf5g82+V3BSKep5eyuH43zYPZQTXTjJawtKzzy+VjVZEFnLaDPFQoBnTIWN1KS0sxfzeiAUOTRdRHV7i3/dMPo3l9AN/v2BWQX/M/yEUG0QrdslhKNOckSjQAPQwrTRV7d5ADNWqr/eIxV7gZ9gfp/QoKtm3M6vCCs1k8jiAtpOa/a/b5VpTthHnuFnw6u9JIKf7/u7wHXLVghNhTeN0LELaxkVkgQw8+svJ3DHAbO16IA476/dqtfLZ+HayX8Zxw5Pg5v1CcHTCVu8rR+eLHrO/NbXUqjYjfYZAO5mJmPrPhPei18VRGy56OFwt6MexR1F3gvWlCYsEfKLWCBqgISEaq2+qFEAR/hI4VCGa5oV7Xdi3Aw8ohFQ2yjaU0VAA7eAUZhTHe1YCIL0mXRz5fu8yZYlEXu4sUGf3A6H8Bbn/0E1W3M1cuWrsLKgocy5y/0REn/kCf1hQceyO2igVtTdsL0oD2VqKAwBXc+uEVIdfVHLWcvcTkbqpN9MRn9oMc4YiFAJyohSn9x+OGrrMmjsOJ6Vjs=
    app: waxpoetic-staging
    on:
      repo: waxpoetic/waxpoetic
  - provider: heroku # production (www.waxpoeticrecords.com)
    api_key:
      secure: k0UI3UjH1CESus6bSA9jd0IBm0TappHKxOq4BsraBJSKEzHF/DShFiNcbYXn/Vlo5qXBlepWjGeao5i3O0UToiHGECN7GCp3JeEhm3LG7+HkOKKxEYBaVw3ynVeBseTVnyqFxvWL2+WTJddf5g82+V3BSKep5eyuH43zYPZQTXTjJawtKzzy+VjVZEFnLaDPFQoBnTIWN1KS0sxfzeiAUOTRdRHV7i3/dMPo3l9AN/v2BWQX/M/yEUG0QrdslhKNOckSjQAPQwrTRV7d5ADNWqr/eIxV7gZ9gfp/QoKtm3M6vCCs1k8jiAtpOa/a/b5VpTthHnuFnw6u9JIKf7/u7wHXLVghNhTeN0LELaxkVkgQw8+svJ3DHAbO16IA476/dqtfLZ+HayX8Zxw5Pg5v1CcHTCVu8rR+eLHrO/NbXUqjYjfYZAO5mJmPrPhPei18VRGy56OFwt6MexR1F3gvWlCYsEfKLWCBqgISEaq2+qFEAR/hI4VCGa5oV7Xdi3Aw8ohFQ2yjaU0VAA7eAUZhTHe1YCIL0mXRz5fu8yZYlEXu4sUGf3A6H8Bbn/0E1W3M1cuWrsLKgocy5y/0REn/kCf1hQceyO2igVtTdsL0oD2VqKAwBXc+uEVIdfVHLWcvcTkbqpN9MRn9oMc4YiFAJyohSn9x+OGrrMmjsOJ6Vjs=
    app: waxpoetic
    on:
      repo: waxpoetic/waxpoetic
      tags: true
