default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: wax_poetic_development

test:
  <<: *default
  database: wax_poetic_test

staging:
  <<: *default
  database: wax_poetic_staging
  username: wax_poetic
  password: <%= ENV['DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: wax_poetic_production
  username: wax_poetic
  password: <%= ENV['DATABASE_PASSWORD'] %>
