default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: db

development:
  <<: *default
  database: wax_poetic_development

test:
  <<: *default
  database: wax_poetic_test

staging:
  <<: *default
  database: wax_poetic_staging

production:
  <<: *default
  database: wax_poetic_production
  username: waxpoetic
  password: <%= ENV['DATABASE_PASSWORD'] %>
