default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

evelopment:
  <<: *default
  database: wax_poetic_development

test:
  <<: *default
  database: wax_poetic_test

staging:
  <<: *default
  database: wax_poetic_staging
  host: <%= ENV['DATABASE_HOST'] %>
  username: wax_poetic
  password: <%= ENV['DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: wax_poetic_production
  host: <%= ENV['DATABASE_HOST'] %>
  username: wax_poetic
  password: <%= ENV['DATABASE_PASSWORD'] %>
