default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: wax_poetic_development

test:
  <<: *default
  database: wax_poetic_test

production:
  <<: *default
  database: wax_poetic_production
  host: <%= ENV['DATABASE_HOST'] %>
  username: waxpoetic
  password: <%= ENV['DATABASE_PASSWORD'] %>
