# Use mocked attributes for local development and testing
development:
  secret_key_base: bde445865a303bc64d780a5902d6176b68e022258b3341c6c400583422b54afd5cb2f86713ea88734d264a5989fd6971d6e018f81456ca8128a3920e86bf9a2f
  admin_user:
    email: admin@example.com
    password: admin123
    password_confirmation: admin123
    remember_me: true
test:
  secret_key_base: bde445865a303bc64d780a5902d6176b68e022258b3341c6c400583422b54afd5cb2f86713ea88734d264a5989fd6971d6e018f81456ca8128a3920e86bf9a2f
  admin_user:
    email: admin@example.com
    password: admin123
    password_confirmation: admin123
    remember_me: true
  test: # test_promoter
    api_key: "helloI4mAPIKey"
    secret_key: "0hH3llS3cretY34h"
  google_tag_id: GTM-12345
  bitly_api_key: 5b0ffd90041956b31acdfb2183f78b65
  mailchimp_api_key: 278bc5b3e9e4827b47b62b4b7d873bfc
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  cdn_host: <%= ENV["CDN_HOST"] %>
  admin_user:
    email: <%= ENV['ADMIN_USER_EMAIL'] %>
    password: <%= ENV['ADMIN_USER_PASSWORD'] %>
    password_confirmation: <%= ENV['ADMIN_USER_PASSWORD'] %>
    remember_me: true
  soundcloud:
    client_id: <%= ENV['SOUNDCLOUD_CLIENT_ID'] %>
    client_secret: <%= ENV['SOUNDCLOUD_CLIENT_SECRET'] %>
    refresh_token: <%= ENV['SOUNDCLOUD_REFRESH_TOKEN'] %>
  google_tag_id: <%= ENV['GOOGLE_TAG_ID'] %>
  bitly_api_key: <%= ENV['BITLY_API_KEY'] %>
  mailchimp_api_key: <%= ENV['MAILCHIMP_API_KEY'] %>
  mailchimp_list_id: <%= ENV['MAILCHIMP_LIST_ID'] %>
  sendgrid_username: <%= ENV['SENDGRID_USERNAME'] %>
  sendgrid_password: <%= ENV['SENDGRID_PASSWORD'] %>
  aws:
    :access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
    :secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
    :region: <%= ENV["AWS_REGION"] %>
    :bucket: <%= ENV["AWS_S3_BUCKET_NAME"] %>
  twitter:
    consumer_key: <%= ENV['TWITTER_CONSUMER_KEY'] %>
    consumer_secret: <%= ENV['TWITTER_CONSUMER_SECRET'] %>
    access_token: <%= ENV['TWITTER_ACCESS_TOKEN'] %>
    access_token_secret: <%= ENV['TWITTER_ACCESS_TOKEN_SECRET'] %>
