# Set up the base config for dev/test.
development:
  secret_key_base: bde445865a303bc64d780a5902d6176b68e022258b3341c6c400583422b54afd5cb2f86713ea88734d264a5989fd6971d6e018f81456ca8128a3920e86bf9a2f
  aws:
    access_key_id: ''
    secret_access_key: ''

test:
  secret_key_base: 8968cf339990b85b7025542d6912001c865eafdf3b8f9877df365552c0289e20d3f3bacd19eaecef88510367a1a0f3918703f1681d448ea3c0a0a6ebe01051e1
  aws:
    access_key_id: ''
    secret_access_key: ''

# Staging pretty much uses the same config as production
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws:
    access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
    secret_access_key: <%= ENV['AWS_SECRET_KEY_ID'] %>

# Store all config for production in environment vars for security
# reasons
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws:
    access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
    secret_access_key: <%= ENV['AWS_SECRET_KEY_ID'] %>
