# These attributes are used to mock out the site for development
# purposes.
mocked: &mocked
  secret_key_base: bde445865a303bc64d780a5902d6176b68e022258b3341c6c400583422b54afd5cb2f86713ea88734d264a5989fd6971d6e018f81456ca8128a3920e86bf9a2f
  admin_user:
    email: admin@example.com
    password: admin123
    password_confirmation: admin123
    remember_me: true
  test: # test_promoter
    api_key: "helloI4mAPIKey"
    secret_key: "0hH3llS3cretY34h"
  soundcloud:
    client_id: 2f78706062fc92d88f018be7b5ec7b33
    client_secret: c0f91a73e0656a61902abd77e8dd0642
  google_tag_id: GTM-12345
  bitly_api_key: 5b0ffd90041956b31acdfb2183f78b65
  mailchimp_api_key: 278bc5b3e9e4827b47b62b4b7d873bfc

# These are the actual attributes we are using in production.
secure: &secure
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  admin_user:
    email: <%= ENV['ADMIN_USER_EMAIL'] %>
    password: <%= ENV['ADMIN_USER_PASSWORD'] %>
    password_confirmation: <%= ENV['ADMIN_USER_PASSWORD'] %>
    remember_me: true
  soundcloud:
    client_id: <%= ENV['SOUNDCLOUD_CLIENT_ID'] %>
    client_secret: <%= ENV['SOUNDCLOUD_CLIENT_SECRET'] %>
  google_tag_id: <%= ENV['GOOGLE_ANALYTICS_ID'] %>
  bitly_api_key: <%= ENV['BITLY_API_KEY'] %>
  mailchimp_api_key: <%= ENV['MAILCHIMP_API_KEY'] %>

# Use mocked attributes for local development and testing
development:
  <<: *mocked
test:
  <<: *mocked

# Use secure attributes for deployed environments
staging:
  <<: *secure
production:
  <<: *secure
