# These attributes are used to mock out the site for development
# purposes.
default: &default
  secret_key_base: bde445865a303bc64d780a5902d6176b68e022258b3341c6c400583422b54afd5cb2f86713ea88734d264a5989fd6971d6e018f81456ca8128a3920e86bf9a2f
  aws:
    access_key_id: a-very-secret-key
    secret_access_key: a-much-more-secret-key
  admin_user:
    email: admin@example.com
    password: admin123
    password_confirmation: admin123
    remember_me: true
  test: # test_promoter
    api_key: "helloI4mAPIKey"
    secret_key: "0hH3llS3cretY34h"
  google_analytics_id: 'UA-00001176-0'
  bitly_api_key: ""
  stripe_secret_key: <%= SecureRandom.hex.to_s %>
  stripe_publishable_key: <%= "pk_#{SecureRandom.hex.to_s}" %>
  segment_write_key: <%= SecureRandom.hex.to_s %>
  mailchimp_api_key: <%= SecureRandom.hex.to_s %>
  circle_token: <%= SecureRandom.hex.to_s %>
  redis_url: 'redis://cache:5678'

# These are the actual attributes we are using in production.
secure: &secure
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws:
    access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
    secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  admin_user:
    email: <%= ENV['ADMIN_USER_EMAIL'] %>
    password: <%= ENV['ADMIN_USER_PASSWORD'] %>
    password_confirmation: <%= ENV['ADMIN_USER_PASSWORD'] %>
    remember_me: true
  soundcloud:
    client_id: <%= ENV['SOUNDCLOUD_CLIENT_ID'] %>
    client_secret: <%= ENV['SOUNDCLOUD_CLIENT_SECRET'] %>
  google_analytics_id: <%= ENV['GOOGLE_ANALYTICS_ID'] %>
  bitly_api_key: <%= ENV['BITLY_API_KEY'] %>
  stripe_secret_key: <%= ENV['STRIPE_SECRET_KEY'] %>
  stripe_publishable_key: <%= ENV['STRIPE_PUBLISHABLE_KEY'] %>
  segment_write_key: <%= ENV['SEGMENT_WRITE_KEY'] %>
  mailchimp_api_key: <%= ENV['MAILCHIMP_API_KEY'] %>
  circle_token: <%= ENV['COOKBOOK_CIRCLE_TOKEN'] %>

# Use mocked attributes for local development and testing
development:
  <<: *default
test:
  <<: *default

# Use secure attributes for deployed environments
staging:
  <<: *secure
production:
  <<: *secure
